### PR TITLE
Accounting for changes to Parser API queries and mutations

### PR DESCRIPTION
**Pull request by AlexanderBrandborg**
Not ready for merge, API changes have to get into Humio first.
* Updates parser code to fit with future changes in Humio API. Using parser Id rather than parser name on queries and mutations.

### CODE REVIEW

**Comment by danielamkaer** [comment]
What's up with Hey.yaml?
Can you add `ID string` to the `Parser` struct?

**Comment by AlexanderBrandborg** [comment]
> What's up with Hey.yaml?
> Can you add `ID string` to the `Parser` struct?

Deleted that file.
Not sure what the purpose of that it? To me it seems like that struct is mostly used in structuring output from the API or adding a parser, which doesn't require an ID, and since the ID and name of a parser is equal, I don't think it makes sense to necessarily show both on output.

**Comment by danielamkaer** [comment]
Why do we have both an ID and Name field on a parser, if they're equal?

My point is, if the input to a command is an ID, it should be possible to get that ID from a list operation.

**Comment by AlexanderBrandborg** [comment]
> Why do we have both an ID and Name field on a parser, if they're equal?
> 
> My point is, if the input to a command is an ID, it should be possible to get that ID from a list operation.

They're equal because of legacy. So it's something we have to work around, and things easily can end up getting a bit messy. I believe it was a decision taken, before ids were set to be GUIDs. 

To users they're still giving the parser 'name' on output, but that just happens to be equal to the id. So the list command still gives them the info needed to do further operations on parsers. We decided that on the API we wanted to be consistent with how we fetch entities, hence the switch from name to id.

**Comment by danielamkaer** [comment]
But are names and IDs eventually going to be different? Then I think IDs should be listed.

**Comment by AlexanderBrandborg** [comment]
> But are names and IDs eventually going to be different? Then I think IDs should be listed.

I don't think there are plans to change it in the near future, from what I know.
The problem is that changing it now, would impact already stored parsers on the user-side.

Not saying that this is the prettiest solution, but from an API perspective it is more consistent. :)

**Pull request closed without merging**
