### PR TITLE
Add code generation for GraphQL enum & mutation input types

### PR DESCRIPTION
**Pull request by bderrly**
Add code genration for the input types and enumerations used on the Logscale GraphQL endpoint. The generation code is a modified version of that used in the https://github.com/shurcooL/graphql module.

I am looking for feedback on this as a path forward before I embark on the work to fully incorporate it and remove duplicate types already found in the CLI code.

### CODE REVIEW

**Comment by bderrly** [comment]
Building this made me wonder if the API should be split off into a separate git repository and thus Go module from the CLI. This would remove the need for the go workspace change I made here but also be a cleaner separation of concerns to prevent bleed over into the API patterns to meet the needs of the CLI.

**Comment by bderrly** [comment]
@SaaldjorMike, one concern that I recall having about this PR is related to the backwards compatibility of the GraphQL API. If we generate this code and tie it to a specific CLI (or eventually API) release version then do we have guarantees that it will work for people running an older version of Logscale? Will we need to generate different releases of the generated API to match each stable Logscale release?

**Comment by SaaldjorMike** [comment]
@bderrly With https://github.com/humio/cli/pull/179 being merged in, we will from now on generate Go code from graphql queries/mutations based of the schema. This means that we going forward will be code-generating the Go code for interacting with the LogScale GraphQL API in https://github.com/humio/cli for things relevant to the humioctl tool, and separately within https://github.com/humio/humio-operator/ for things we need in that project. This is not limited to enums or input types.

**Comment by bderrly** [comment]
I am glad to see the changes in #179!

**Pull request closed without merging**
